// Copyright (c) 2026 Likeon. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace SigilMovementModeTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flying)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swimming)
}

namespace SigilRotationModeTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
}

namespace SigilMovementStateTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jog)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint)
}

/**
 * Movement set tags. USigilMovementSystemComponent::SetMovementSet already declares
 * Meta = (Categories = "Sigil.Movement.Set"), but no tag was ever defined under it,
 * so every host had to invent its own. These are the canonical ones.
 * 运动集标签。SetMovementSet 早已声明分类为 Sigil.Movement.Set，却没有任何标签定义在该命名空间下，
 * 导致每个宿主各自造标签、必然漂移。此处补齐规范标签。
 */
namespace SigilMovementSetTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouched)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ladder)
	/** Aiming-down-sights and guarding sets, each with a crouched variant. 瞄准与格挡运动集，各带蹲伏变体。 */
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ADS)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ADS_Crouched)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Guard)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Guard_Crouched)
}

namespace SigilOverlayModeTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
}

namespace SigilSMTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir_Jump)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir_Fall)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Idle)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Start)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Cycle)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Stop)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Pivot)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Land)

}
