// Copyright (c) 2026 Likeon. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace SigilMovementModeTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flying)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swimming)
}

namespace SigilRotationModeTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
}

namespace SigilMovementStateTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jog)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint)
}

namespace SigilOverlayModeTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
}

namespace SigilSMTags
{
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir_Jump)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir_Fall)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Idle)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Start)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Cycle)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Stop)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Pivot)
	SIGILMOVEMENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded_Land)

}
