// Copyright 2025 RedMoonGames All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"


GENERICGAMEPLAYABILITIES_API DECLARE_LOG_CATEGORY_EXTERN(LogGGA_Ability, Log, All);

GENERICGAMEPLAYABILITIES_API DECLARE_LOG_CATEGORY_EXTERN(LogGGA_AbilitySystem, Log, All);

GENERICGAMEPLAYABILITIES_API DECLARE_LOG_CATEGORY_EXTERN(LogGGA_Tasks, Log, All);
