// Copyright 2025 RedMoonGames All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"


namespace GGA_AbilityActivateFailTags
{
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown)
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost)
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TagsBlocked);
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TagsMissing);
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Networking);
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivationGroup);
}

namespace GGA_AbilityTraitTags
{
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivationOnSpawn)
	GENERICGAMEPLAYABILITIES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Persistent)

}
